In [2]:
import pandas as pd
import numpy as np

In [3]:
maps = pd.read_csv('maps.csv')
maps

    ind            map   default   neutral     dim  passability
0     0      Andromeda         1         6   64*64            1
1     1          Arena         1         6   32*32            1
2     2            Bog         1         6   64*64            1
3     3       Branches         1         6   64*64            1
4     4        Chevron         3         4   64*32            1
5     5       Corridor         1         6   33*40            1
6     6            Cow         2         6   50*80            1
7     7    CrossStitch         1         4   64*64            1
8     8    CrownJewels         1         6   64*32            1
9     9     ExesAndOhs         1         6   64*42            1
10   10   FiveOfHearts         1         6   64*64            1
11   11       Gridlock         1         6   64*64            1
12   12       Illusion         1         4   35*36            1
13   13     NotAPuzzle         1         6   64*64            1
14   14        Rainbow         1         2   50*32            1
15   15      SlowMusic         1         6   64*48            1
16   16      SnowFlake         1         2   35*36            1

In [56]:
maps.columns

Index([              'ind',              ' map',          ' default',
                ' neutral',              ' dim',       'passability',
                   'width',            'height', ('width', 'height')],
      dtype='object')

In [47]:
maps['width'] = maps[' dim'].str.split('*', expand=True)[0]

In [49]:
maps['height'] = maps[' dim'].str.split('*', expand=True)[1]

In [50]:
maps.head()

,ind,map,default,neutral,dim,passability,width,height,"(width, height)"
0,0,Andromeda,1,6,64*64,1,64,64,64
1,1,Arena,1,6,32*32,1,32,32,32
2,2,Bog,1,6,64*64,1,64,64,64
3,3,Branches,1,6,64*64,1,64,64,64
4,4,Chevron,3,4,64*32,1,64,32,64

In [57]:
maps.drop(columns=('width', 'height'))

    ind            map   default   neutral     dim  passability width height
0     0      Andromeda         1         6   64*64            1    64     64
1     1          Arena         1         6   32*32            1    32     32
2     2            Bog         1         6   64*64            1    64     64
3     3       Branches         1         6   64*64            1    64     64
4     4        Chevron         3         4   64*32            1    64     32
5     5       Corridor         1         6   33*40            1    33     40
6     6            Cow         2         6   50*80            1    50     80
7     7    CrossStitch         1         4   64*64            1    64     64
8     8    CrownJewels         1         6   64*32            1    64     32
9     9     ExesAndOhs         1         6   64*42            1    64     42
10   10   FiveOfHearts         1         6   64*64            1    64     64
11   11       Gridlock         1         6   64*64            1    64     64
12   12       Illusion         1         4   35*36            1    35     36
13   13     NotAPuzzle         1         6   64*64            1    64     64
14   14        Rainbow         1         2   50*32            1    50     32
15   15      SlowMusic         1         6   64*48            1    64     48
16   16      SnowFlake         1         2   35*36            1    35     36

In [64]:
maps['mucks in grid'] = (maps['width'].astype('int64')/5).apply(np.ceil) * (maps['height'].astype('int64')/5).apply(np.ceil)

In [65]:
maps.head(17)

,ind,map,default,neutral,dim,passability,width,height,"(width, height)",mucks in grid
0,0,Andromeda,1,6,64*64,1,64,64,64,169.0
1,1,Arena,1,6,32*32,1,32,32,32,49.0
2,2,Bog,1,6,64*64,1,64,64,64,169.0
3,3,Branches,1,6,64*64,1,64,64,64,169.0
4,4,Chevron,3,4,64*32,1,64,32,64,91.0
5,5,Corridor,1,6,33*40,1,33,40,33,56.0
6,6,Cow,2,6,50*80,1,50,80,50,160.0
7,7,CrossStitch,1,4,64*64,1,64,64,64,169.0
8,8,CrownJewels,1,6,64*32,1,64,32,64,91.0
9,9,ExesAndOhs,1,6,64*42,1,64,42,64,117.0
10,10,FiveOfHearts,1,6,64*64,1,64,64,64,169.0
11,11,Gridlock,1,6,64*64,1,64,64,64,169.0
12,12,Illusion,1,4,35*36,1,35,36,35,56.0
13,13,NotAPuzzle,1,6,64*64,1,64,64,64,169.0
14,14,Rainbow,1,2,50*32,1,50,32,50,70.0
15,15,SlowMusic,1,6,64*48,1,64,48,64,130.0
16,16,SnowFlake,1,2,35*36,1,35,36,35,56.0

In [70]:
maps = maps.drop(columns=[' dim',('width', 'height'), 'passability','ind'] )

In [71]:
maps

              map   default   neutral width height  mucks in grid
0       Andromeda         1         6    64     64          169.0
1           Arena         1         6    32     32           49.0
2             Bog         1         6    64     64          169.0
3        Branches         1         6    64     64          169.0
4         Chevron         3         4    64     32           91.0
5        Corridor         1         6    33     40           56.0
6             Cow         2         6    50     80          160.0
7     CrossStitch         1         4    64     64          169.0
8     CrownJewels         1         6    64     32           91.0
9      ExesAndOhs         1         6    64     42          117.0
10   FiveOfHearts         1         6    64     64          169.0
11       Gridlock         1         6    64     64          169.0
12       Illusion         1         4    35     36           56.0
13     NotAPuzzle         1         6    64     64          169.0
14        Rainbow         1         2    50     32           70.0
15      SlowMusic         1         6    64     48          130.0
16      SnowFlake         1         2    35     36           56.0

In [72]:
maps['avg mucks/ec'] = maps['mucks in grid']/(maps[' default'].astype('int64') + maps[' neutral'].astype('int64')/2)

In [73]:
maps

,map,default,neutral,width,height,mucks in grid,avg mucks/ec
0,Andromeda,1,6,64,64,169.0,42.250000
1,Arena,1,6,32,32,49.0,12.250000
2,Bog,1,6,64,64,169.0,42.250000
3,Branches,1,6,64,64,169.0,42.250000
4,Chevron,3,4,64,32,91.0,18.200000
5,Corridor,1,6,33,40,56.0,14.000000
6,Cow,2,6,50,80,160.0,32.000000
7,CrossStitch,1,4,64,64,169.0,56.333333
8,CrownJewels,1,6,64,32,91.0,22.750000
9,ExesAndOhs,1,6,64,42,117.0,29.250000
10,FiveOfHearts,1,6,64,64,169.0,42.250000
11,Gridlock,1,6,64,64,169.0,42.250000
12,Illusion,1,4,35,36,56.0,18.666667
13,NotAPuzzle,1,6,64,64,169.0,42.250000
14,Rainbow,1,2,50,32,70.0,35.000000
15,SlowMusic,1,6,64,48,130.0,32.500000
16,SnowFlake,1,2,35,36,56.0,28.000000

In [74]:
maps.to_csv('maps.csv')